apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-simon
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-simon
  template:
    metadata:
      labels:
        app: portfolio-simon
    spec:
      containers:
<<<<<<< HEAD
      - name: monportfolio
        image: ghcr.io/simongallien/portfolio-simon:latest
=======
      - name: portfolio-simon
        image: ghcr.io/simongallien/portfolio-simon:latest  # Image Docker de ton portfolio
>>>>>>> 0432308 (Fix: Change deployment name from monportfolio to portfolio-simon)
        ports:
        - containerPort: 80
