apiVersion: apps/v1
kind: Deployment
metadata:
  name: monportfolio
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monportfolio
  template:
    metadata:
      labels:
        app: monportfolio
    spec:
      containers:
      - name: monportfolio
        image: ghcr.io/simongallien/portfolio-simon:latest
        ports:
        - containerPort: 80
